version: '3'

services:
  influxdb:
    image: influxdb
    container_name: influx
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - 8086:8086
    expose:
      - "8086" 
    environment:  
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_ENABLED=${INFLUXDB_ADMIN_ENABLED}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
    networks: 
      - app-network
  grafana:
    image: grafana/grafana:master
    user: "0" 
    ports: 
      - "3000:3000"
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
    networks:
      - app-network  
  telegraf:
    image: telegraf
    container_name: telegrafMob
    env_file:
      - .env
    links:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ${LOG_NGINX}:/var/log/nginx/access.log:ro
      - ./telegraf/logs:/var/log/telegraf
    networks:
      - app-network    
networks: 
  app-network:
    driver: bridge